### ISSUE TITLE
Ajuste de responsividade nos eventos

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#11]
# Problema

Em telas pequenas, os cards do eventos ficam muito pequenos e dificultam a leitura dos detalhes.
Eles deveriam ocupar a tela toda em telas menores, e se comportar como uma lista um abaixo do outro.

<img width="495" alt="Screenshot 2024-06-02 at 17 58 00" src="https://github.com/Fernanda-Kipper/eventostec-frontend/assets/61896274/a3a89176-fe12-47e5-82e0-9114b8a6a4d0">

**Comment by emnesty** [comment]
Posso pegar esse

**Comment by emnesty** [comment]
Fiz rapidão os ajustes aqui:

![Captura de Tela 2024-06-03 às 10 28 59](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/7916851/6c91d9c4-7159-4934-bfc3-4f3c9a580b7f)
![Captura de Tela 2024-06-03 às 10 29 22](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/7916851/0fbea591-8ce8-495a-91cf-1426c51f5ee3)
![Captura de Tela 2024-06-03 às 10 29 35](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/7916851/de67dc25-30c4-420b-b36d-486cfce40e97)
![Captura de Tela 2024-06-03 às 10 29 48](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/7916851/1afab153-8566-46a2-b379-640e34cff04c)

**Comment by pvbinatto** [comment]
Cria o PR agora dessa funcionalidade

**Comment by emnesty** [comment]
> Cria o PR agora dessa funcionalidade

Criado

**Comment by Fernanda-Kipper** [comment]
Boa! Vou encerrar a issue
