### ISSUE TITLE
Criar tela de detalhes do evento

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#12]
# Problema

Ao clicar no card do evento, o usuário é redirecionado para a URL cadastrada desse evento.

Porém, a ideia é que seja aberta uma página com os detalhes desse evento, e com alguns cupons de desconto que tenham sido cadastrados. E então o usuário pode optar por ser redirecionado ao site do evento para comprar ou saber mais detalhes.

## Funcionalidades obrigatórias

- Banner do Evento no topo (tipo Sympla)
- Titulo, Local e Data
- Botão para acessar o site oficial do evento
- Lista de cupons cadastrados pela comunidade
- Forms para cadastrar novo cupom do evento

**Comment by emnesty** [comment]
Posso criar a base da tela nova, mas teria que ver s questão do redirecionamento dinâmico? Ou algo do tipo para cada evento?

**Comment by Ferreira-Luiz** [comment]
faz a tela que eu faco o redirecionamente @emnesty. e ajusto uq for necessario
