### ISSUE TITLE
Implementar uma biblioteca de componentes?

### ISSUE THREAD

**Issue by brunordgs** [Fernanda-Kipper/eventostec-frontend#16]
Não desenvolvo nada utilizando o Angular, porém eu vi que ele tem uma biblioteca parecida com o [shadcn/ui](https://ui.shadcn.com) que se chama [spartan/ui](https://www.spartan.ng), talvez ajude caso vocês queiram agilizar o design.

**Comment by emnesty** [comment]
Também não desenvolvo em Angular e ter algo parecido com o **shadcn** parece uma boa ideia.

**Comment by wanderhungerbuhler** [comment]
Eu já testei o Spartan/UI fazendo alguns testes em estudo do Angular, mas ainda é uma Lib em crescimento e faltam ainda recursos que na minha visão para este momento, seria muito importante.

Em contrapartida, eu tenho utilizado bastante o [PrimeNG](https://primeng.org/) que sem dúvidas é a mais completa do mercado. Com base nisso, vou sugerir uma PR com essa implementação.
