### ISSUE TITLE
Adicionar um tamanho pre fixado para os cards de eventos e um split no texto 

### ISSUE THREAD

**Issue by joaovitormp1998** [Fernanda-Kipper/eventostec-frontend#26]
Fiz alguns teste de responsividade e não ficou um vizual mto agravel em mobile para multiplos cards
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/1e42dee7-b681-4616-85ca-e552ce237f58)
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/7f40b566-5975-4785-8563-ed85aea01fc8)
Acredito que uma limitaçao dos cards ou reduçao de fonte e tamanho de imagem ornamentariam melhor
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/818a6be8-7a74-444b-8bc2-fbc155092b27)
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/e8124975-dec3-4ad2-9d64-9105a9bd38e3)

**Comment by emnesty** [comment]
Nesse caso precisamos definir quais infos vão ser colocadas no texto e a partir disso podemos definir um tamanho minimo de largura pros cards, dai acredito que o grid fica responsável por ajustar com base nessas infs

**Comment by LFzinn** [comment]
ja estou fazendo isso. criei ja a parte de adicionar evento tbm

**Comment by Ferreira-Luiz** [comment]
ja fiz isso e ja estou fazendo o crud para lidar com os eventos

**Comment by joaovitormp1998** [comment]
boa @LFzinn

**Comment by joaovitormp1998** [comment]
conferi aqui ja e ta file 
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/a6561fa8-4550-460c-b76c-60bcb95914ef)
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/d9165760-545b-402b-83da-57b88aa66dda)
@Fernanda-Kipper
