### ISSUE TITLE
Adicionar footer

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#34]
## Problema

Precisamos de um footer que destaque o projeto está sendo desenvolvido e mantido pela comunidade. 

Pensei em algo tipo:  "Desenvolvido com 💜 pela comunidade KipperDev"

### Exemplo:

<img width="537" alt="Screenshot 2024-06-08 at 19 14 43" src="https://github.com/Fernanda-Kipper/eventostec-frontend/assets/61896274/7b885567-83f2-406c-950d-8bced5bc71a5">

**Comment by joaovitormp1998** [comment]
Feito aqui subindo PR
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/94e8bbd9-f162-4727-b6b1-19d28b107d80)
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/49036365/a1923480-3954-4baf-a8d6-ec24bdf1b9c0)
