### ISSUE TITLE
[BUG] Filtro para de funcionar

### ISSUE THREAD

**Issue by LeoUpperThrower4** [Fernanda-Kipper/eventostec-frontend#48]
https://github.com/user-attachments/assets/fc4540d9-aa10-42d4-b3b1-b919b482ecc1

**Comment by BernardoSemiOficial** [comment]
Esse problemas consigo resolver.
Eu pelo menos encontrei alguns:
- Não limpa filtro corretamente
- Os valores selecionados no select não são exibidos as vezes.
- Quando não encontra nenhum resultado deveria ao menos aparecer uma mensagem de "Sem resultados encontrados."
