### ISSUE TITLE
Padronizar selects

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#53]
Devemos padronizar o layout do site do eventos tec. 
Para isso, precisamos padronizar os inputs ao longo da plataforma, principalmente os selects que na home page, dentro do modal, são de uma forma, e dentro do cadastro de eventos são de outra.
É necessário usar o mesmo select, da lib PrimeNG, em toda a interface.

**Select correto:**
<img width="525" alt="Screenshot 2024-07-14 at 12 08 31" src="https://github.com/user-attachments/assets/923daf73-c9a1-409d-8f08-3b2cade1dfdd">

**Select errado:**

<img width="696" alt="Screenshot 2024-07-14 at 12 09 11" src="https://github.com/user-attachments/assets/caeae77b-5fa7-4e78-aa95-3ace5d116e92">

**Comment by BernardoSemiOficial** [comment]
Consigo tratar esse problema também.
Vou abrir PR para essa correção.
