### ISSUE TITLE
Ajustar cor do botão de filtro

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#6]
# Problema

O botão de filtrar deve possuir a mesma cor e comportamento que o botão de adicionar novo evento.

# Screenshots

<img width="117" alt="Screenshot 2024-06-02 at 17 52 08" src="https://github.com/Fernanda-Kipper/eventostec-frontend/assets/61896274/48ffe8dd-a5ee-4ae7-a12e-693990051e2b">
<img width="209" alt="Screenshot 2024-06-02 at 17 52 05" src="https://github.com/Fernanda-Kipper/eventostec-frontend/assets/61896274/855fa975-9b2e-40fd-aeed-f486ad22f46a">

**Comment by LivHelen12** [comment]
1. O ícone de + no botão de filtro deve ser mantido?

**Comment by Fernanda-Kipper** [comment]
> 1. O ícone de + no botão de filtro deve ser mantido?

Simmm! Só muda o BG mesmo
