### ISSUE TITLE
Criar tela para cadastro de evento

### ISSUE THREAD

**Issue by Fernanda-Kipper** [Fernanda-Kipper/eventostec-frontend#7]
# Problema

Ao clicar no botão Adicionar novo evento, o usuário não é redirecionado para nenhum lugar onde consiga adicionar eventos.
Para isso é necessário criar uma nova página, que seja o formulário de cadastro de eventos.

## Campos obrigatórios no formulário

- Titulo
- Descrição
- Banner -> Upload de Foto
- Local -> Usar o mesmo select do filtro para escolher Estado -> Cidade
- Data

## Campos opcionais

- Cupons de desconto para o evento

**Comment by BernardoSemiOficial** [comment]
Vou contribuir com essa parte. Pode deixar 💯

**Comment by Fernanda-Kipper** [comment]
Valeuu @BernardoSemiOficial! 
Já criei a tela (ta dentro do componente `register-event`), falta colocar os campos de Cupom e Banner, e deixar mais bontinho heheh

**Comment by BernardoSemiOficial** [comment]
@Fernanda-Kipper criei essa tela aqui. 
Posso subir o PR para dar uma olhada e vê no que dá para aproveitar.
![image](https://github.com/Fernanda-Kipper/eventostec-frontend/assets/114026716/caa0aa91-2e60-46af-9682-9cf6214d0b69)
